CHARS_TO_PREDICT = 3

# encodings for languages of characters
ENG = 0
RUS = 1
CHI = 2
UNK = 3
SPACE_DELIMITED_LANGS = {ENG, RUS}
NON_SPACE_DELIMITED_LANGS = {CHI}

# Prefix token for ngrams or anything that needs to start with nonempty context
PREFIX_TOKEN = "<sos>"

# returns the language of the character 'ch'
# (note this does not take into account edge cases, like japanese having
# the same unicode characters as chinese)
# Either: self.ENG, self.RUS, self.CHI, or self.UNK if could not be determined
def get_lang(ch):
    code = ord(ch)
    if 0x0041 <= code <= 0x007A or 0x00C0 <= code <= 0x024F:
        return self.ENG
    elif 0x0400 <= code <= 0x04FF or 0x0500 <= code <= 0x052F:
        return self.RUS
    elif 0x4E00 <= code <= 0x9FFF or 0x3400 <= code <= 0x4DBF:
        return self.CHI
    else:
        return self.UNK

# returns the list of tokens that make up a line
def tokenize_line(line):
        line_with_spaces_around_tokens = (
            "".join(
                f" {c} " if self.get_lang(c) in NON_SPACE_DELIMITED_LANGS else c
                for c in line
            )
        )
        return line_with_spaces_around_tokens.split()

SAMPLE_ENGLISH_DATA [
    "The cat sat on the mat.",
    "A dog barked loudly outside.",
    "She opened the window slowly.",
    "He drank a cup of coffee.",
    "The sun rose over the hills.",
    "They walked home together.",
    "I forgot my keys again.",
    "The book fell off the table.",
    "Rain tapped against the glass.",
    "The child laughed happily.",
    "She wrote a short email.",
    "He closed the heavy door.",
    "The car stopped at the light.",
    "Birds sang in the morning.",
    "The room felt unusually cold.",
    "I checked the time twice.",
    "The teacher explained the rule.",
    "We waited in a long line.",
    "The phone rang suddenly.",
    "She tied her shoes tightly.",
    "The train arrived on time.",
    "He washed his hands carefully.",
    "The store opened early today.",
    "I heard a strange noise.",
    "The cake smelled delicious.",
    "She smiled at the camera.",
    "The laptop overheated quickly.",
    "He read the instructions carefully.",
    "The lights flickered briefly.",
    "We shared a quiet moment.",
    "The pen ran out of ink.",
    "She packed her bag neatly.",
    "The movie ended abruptly.",
    "I lost track of time.",
    "The floor creaked loudly.",
    "He fixed the broken chair.",
    "The river flowed calmly.",
    "She answered the question correctly.",
    "The meeting started late.",
    "I deleted the old files.",
    "The wind knocked over the sign.",
    "He sharpened his pencil.",
    "The alarm went off early.",
    "She watered the plants.",
    "The bus was crowded.",
    "I made a simple mistake.",
    "The stars were visible tonight.",
    "He folded the paper carefully.",
    "The soup tasted salty.",
    "She turned down the offer.",
    "The clock ticked steadily.",
    "I cleaned my desk.",
    "The snow covered everything.",
    "He missed the deadline.",
    "She locked the door.",
    "The crowd cheered loudly.",
    "I followed the instructions.",
    "The glass shattered instantly.",
    "He checked the results online.",
    "The hallway was empty.",
    "She finished her homework.",
    "The battery needs charging.",
    "I noticed a small error.",
    "The painting looked unfinished.",
    "He took a deep breath.",
    "The elevator stopped abruptly.",
    "She baked fresh bread.",
    "The map was outdated.",
    "I reread the paragraph.",
    "The chair felt uncomfortable.",
    "He saved the document.",
    "The road was slippery.",
    "She skipped breakfast.",
    "The app crashed unexpectedly.",
    "I recognized his voice.",
    "The package arrived damaged.",
    "He counted the change.",
    "The lights were too bright.",
    "She adjusted the settings.",
    "The forest was silent.",
    "I spilled water everywhere.",
    "The answer seemed obvious.",
    "He forgot her birthday.",
    "The file was corrupted.",
    "She lowered her voice.",
    "The doorbell rang twice.",
    "I updated the software.",
    "The air smelled fresh.",
    "He took notes carefully.",
    "The paper tore easily.",
    "She missed the bus.",
    "The room echoed softly.",
    "I learned something new.",
    "The laptop was heavy.",
    "He crossed the street.",
    "The food went cold.",
    "She raised her hand.",
    "The signal was weak.",
    "I backed up the data.",
    "The path was narrow.",
    "He solved the puzzle.",
    "The meeting felt pointless.",
    "She chose the blue one.",
    "The engine made noise.",
    "I checked my email.",
    "The desk was cluttered.",
    "He opened the package.",
    "The screen went dark.",
    "She laughed nervously.",
    "The password was incorrect.",
    "I set a reminder.",
    "The cup cracked slightly.",
    "He stared at the wall.",
    "The room smelled dusty.",
    "She unplugged the charger.",
    "The road curved sharply.",
    "I misplaced my notebook.",
    "The keys jingled softly.",
    "He muted the microphone.",
    "The page loaded slowly.",
    "She cleaned the kitchen.",
    "The weather changed suddenly.",
    "I asked for help.",
    "The chair scraped loudly.",
    "He double checked the math.",
    "The milk expired yesterday.",
    "She erased the board.",
    "The park was empty.",
    "I felt unusually tired.",
    "The file finished downloading.",
    "He cracked his knuckles.",
    "The noise faded away.",
    "She turned off notifications.",
    "The message was unclear.",
    "I paused the video.",
    "The box was sealed.",
    "He closed the tab.",
    "The stairs were steep.",
    "She hummed quietly.",
    "The graph showed growth.",
    "I printed the report.",
    "The window was stuck.",
    "He reset the router.",
    "The cat disappeared.",
    "She checked the lock.",
    "The queue moved slowly.",
    "I heard footsteps.",
    "The screen froze again.",
    "He saved his progress.",
    "The room felt cramped.",
    "She folded the laundry.",
    "The lightbulb burned out.",
    "I reread the email.",
    "The keyboard felt sticky.",
    "He waited patiently.",
    "The coffee cooled down.",
    "She answered politely.",
    "The test was difficult.",
    "I set an alarm.",
    "The bag was heavy.",
    "He scratched his head.",
    "The page was blank.",
    "She missed the call.",
    "The data looked suspicious.",
    "I checked the logs.",
    "The fan made noise.",
    "He pushed the button.",
    "The result surprised me.",
    "She packed lightly.",
    "The hallway smelled clean.",
    "I noticed the typo.",
    "The chair wobbled.",
    "He stretched his arms.",
    "The light felt harsh.",
    "She waited outside.",
    "The email bounced back.",
    "I saved a copy.",
    "The road was blocked.",
    "He closed the app.",
    "The sound was muffled.",
    "She followed the rules.",
    "The answer was wrong.",
    "I fixed the bug.",
    "The desk was scratched.",
    "He typed quickly.",
    "The file uploaded successfully.",
    "She checked the calendar.",
    "The water was cold.",
    "I lost my balance.",
    "The icon disappeared.",
    "He checked the forecast.",
    "The room was bright.",
    "She skipped the question.",
    "The update took hours.",
    "I followed up later.",
    "The handle felt loose.",
    "He organized the files.",
    "The screen was cracked.",
    "She wrote neatly.",
    "The error persisted.",
    "I closed my laptop.",
    "The shelf was dusty.",
    "He nodded silently.",
    "The bus arrived late.",
    "She checked the receipt.",
    "The task felt endless.",
    "I copied the text.",
    "The mouse stopped working.",
    "He adjusted his chair.",
    "The door slammed shut.",
    "She waited nervously.",
    "The numbers didn’t add up.",
    "I restarted the system.",
    "The file was missing.",
    "He glanced at the clock.",
    "The chair was broken.",
    "She opened a new tab.",
    "The sound echoed.",
    "I cleared the cache.",
    "The page refreshed automatically.",
    "He leaned forward.",
    "The room felt quiet.",
    "She closed her notebook.",
    "The app updated overnight.",
    "I checked the version.",
    "The cable was loose.",
    "He frowned slightly.",
    "The page scrolled smoothly.",
    "She saved her work.",
    "The signal dropped again.",
    "I noted the change.",
    "The keyboard clicked loudly.",
    "He paused to think.",
    "The window rattled.",
    "She logged out safely.",
    "The error message appeared.",
    "I wrote a summary.",
    "The chair felt sturdy.",
    "He checked the battery.",
    "The app responded slowly.",
    "She closed the file.",
    "The system rebooted.",
    "I verified the result.",
    "The screen dimmed.",
    "He clicked the link.",
    "The data was accurate.",
    "She reviewed her notes.",
    "The task was simple.",
    "I pressed enter.",
    "The fan stopped spinning.",
    "He reopened the document.",
    "The message was sent.",
    "She checked one last time.",
    "The process completed successfully."
]